## Working with Arrays

Create a 3 x 6-dimensional array, containing only float values. 

In [17]:
import numpy as np
a = np.array([[0, 1, 2, 3], [4, 5, 6, 7]])
print (a)

[[0 1 2 3]
 [4 5 6 7]]


Check the dimension you have created is correct (use “*.shape*”)

In [11]:
a.shape


(2L, 4L)

In [14]:
a[1,3]=19.75
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6, 19]])

Substitute the 5th element from the 2nd row with 19.75.

Extract the 2nd and the 3rd row of the array you created. 

In [ ]:
b = a[]